### ISSUE TITLE
Mitigation Request Feature

### ISSUE THREAD

**Issue by christiankiller** [blockchain-signaling-system/bloss-node#2]
## Intro
This feature _enables_ one of the **main** features of `bloss-dashboard`. 
Thus the `bloss-node` has to take care of the correct flow of information and control flow.
It is at the core of the `bloss-dashboard`s functionality and plays the most crucial role. 

---- 

## TODO
**The mitigation request feature should** 
- [x] ... enable the `bloss-dashboard` to **retrieve** mitigation requests (via websockets)
- [x] ... check if the hash of the report *already exists* since (as of now), each report gets posted 5+ times by bloss-core, this should definitely be addressed on bloss-core side.
- [x] ... enable the `bloss-dashboard` to **react** to mitigation requests (via websockets)
- [x] ... enable the `bloss-dashboard` to **receive** all relevant details regarding mitigation requests (via websockets)
- [x] ... persist the data (mitigation requests with all details) to minimize load for the client (the `bloss-dashboard`) and serve those upon request to the client
- [x] ... MongoDB integration to persist the mitigation requests on the server side for persistence. 
- [x] Make necessary changes to the mongoose schema.
 Add the following properties: 
**State** of which the values are outlined below. 
**Payment** _Has to be mocked._ which is a value in ether (ETH) representing the payment offered to the potential Mitigator
**Reputation** _Has to be mocked._ which is a value representing the Reputation of the Target (Requestor)

### States

-`T` stands for `TARGET`
-`M` stands for `MITIGATOR`
-within the brackets `[]` are the status names.

---- 
* (1) **[T_REQUESTS]** _which means `TARGET` is attacked and is requesting help. This is stage 1 of every new attack report. 
* (2) [**M_DECLINED | M_APPROVES**]
  * (A) **[M_DECLINED]** _which means the `MITIGATOR` looked at the `TARGET`s attack request but decided to decline (mostly due to either fake request, bad reputation or insufficient incentives (payment too low))
  * (B) **[M_APPROVES]** _which means the `MITIGATOR` accepted the request and will start the mitigation process. 

---- 

_more states may become necessary at later stages. as of now this is sufficient_

----

**Comment by christiankiller** [comment]
Payment / Reputation will be done in later Milestones
